# name: Build container

on:
  workflow_call:
    inputs: 
      yq_version: 
        type: string
        required: true
      nvim_version:
        type: string
        required: true
      username: 
        type: string
        required: true
      group_name: 
        type: string
        required: true
      user_id:
        type: string
        required: true
      group_id: 
        type: string
        required: true
    secrets:
      root_pass:
        required: true
      dockerhub_username: 
        required: true
      dockerhub_token: 
        required: true
  
jobs:
  build-container:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os_tag: 
          - noble
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      # - uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: utkusarioglu/bash-devcontainer:latest
      #     file: src/ubuntu.dockerfile
      #     context: src
      #     build-args: |
      #       OS_TAG=${{ matrix.os_tag }}
      #       YQ_VERSION=${{ inputs.yq_version }}
      #       NVIM_VERSION=${{ inputs.nvim_version }}
      #       USERNAME=${{ inputs.username }}
      #       GROUP_NAME=${{ inputs.group_name }}
      #       USER_ID=${{ inputs.user_id }}
      #       GROUP_ID=${{ inputs.group_id }}
      #       ROOT_PASS=${{ secrets.root_pass }}

      - uses: utkusarioglu/devcontainer-build@main
        with:
          docker_hub_username: ${{ secrets.dockerhub_username }}
          docker_hub_token: ${{ secrets.dockerhub_token }}
          image_name: utkusarioglu/bash-devcontainer
          image_tag: latest
          dockerfile_path: src/ubuntu.dockerfile
          build_args: |
            OS_TAG=${{ matrix.os_tag }}
            YQ_VERSION=${{ inputs.yq_version }}
            NVIM_VERSION=${{ inputs.nvim_version }}
            USERNAME=${{ inputs.username }}
            GROUP_NAME=${{ inputs.group_name }}
            USER_ID=${{ inputs.user_id }}
            GROUP_ID=${{ inputs.group_id }}
            ROOT_PASS=${{ secrets.root_pass }}
          devcontainer_subfolder: src
          devcontainer_run_cmd_path: src/scripts/bootstrap/devcontainer-check.sh
          docker_hub_repo_short_description: Ubuntu bash devcontainer
          docker_hub_repo_readme_file_path: src/DOCKER_README.md
