# name: Build container

on:
  workflow_call:
    inputs: 
      # os_tag:
      #   type: string
      #   required: true
      yq_version: 
        type: string
        required: true
      nvim_version:
        type: string
        required: true
      username: 
        type: string
        required: true
      group: 
        type: string
        required: true
    secrets:
      root_pass:
        # type: string
        required: true
      dockerhub_username: 
        # type: string
        required: true
      dockerhub_token: 
        # type: string
        required: true
  
jobs:
  build-container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_tag: 
          - noble
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: utkusarioglu/bash-devcontainer:latest
          file: src/ubuntu.dockerfile
          context: src
          build-args: |
            OS_TAG=${{ matrix.os_tag }}
            YQ_VERSION=${{ inputs.yq_version }}
            NVIM_VERSION=${{ inputs.nvim_version }}
            USERNAME=${{ inputs.username }}
            GROUP=${{ inputs.group }}
            ROOT_PASS=${{ secrets.root_pass }}
            BOOTSTRAP_PATH=${{ inputs.bootstrap_path }}
        
