# name: Build container

on:
  workflow_call:
    inputs: 
      image_tag:
        type: string
        required: true
      yq_version: 
        type: string
        required: true
      nvim_version:
        type: string
        required: true
      username: 
        type: string
        required: true
      group_name: 
        type: string
        required: true
      user_id:
        type: string
        required: true
      group_id: 
        type: string
        required: true
    secrets:
      root_pass:
        required: true
      dockerhub_username: 
        required: true
      dockerhub_token: 
        required: true


jobs:
  build-container:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        images:
          - os_tag: noble
            image_name: ubuntu-devcontainer
            dockerfile_path: src/ubuntu.dockerfile
            docker_context: src
            dockerhub_repo_readme_file_path: src/DOCKER_README.md
            devcontainer_run_cmd_path: /home/dev/scripts/bootstrap/devcontainer-base-check.sh
            devcontainer_subfolder: src
            apt_packages: git jq htop wget tree bats
            apt_packages_silent: software-properties-common

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: utkusarioglu/devcontainer-build-action@main
        with:
          docker_context: ${{ matrix.images.docker_context }}
          dockerhub_username: ${{ secrets.dockerhub_username }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
          image_name: ${{ matrix.images.image_name }}
          image_tag: ${{ inputs.image_tag }}
          dockerfile_path: ${{ matrix.images.dockerfile_path }}
          build_args: |
            OS_TAG=${{ matrix.images.os_tag }}
            YQ_VERSION=${{ inputs.yq_version }}
            NVIM_VERSION=${{ inputs.nvim_version }}
            USERNAME=${{ inputs.username }}
            GROUP_NAME=${{ inputs.group_name }}
            USER_ID=${{ inputs.user_id }}
            GROUP_ID=${{ inputs.group_id }}
            ROOT_PASS=${{ secrets.root_pass }}
            APT_PACKAGES=${{ matrix.images.apt_packages }}
            APT_PACKAGES_SILENT=${{ matrix.images.apt_packages_silent }}
          devcontainer_subfolder: ${{ matrix.images.devcontainer_subfolder }}
          devcontainer_run_cmd_path: ${{ matrix.images.devcontainer_run_cmd_path }}
          dockerhub_repo_short_description: Ubuntu devcontainers
          dockerhub_repo_readme_file_path: ${{ matrix.images.dockerhub_repo_readme_file_path }}
